### PR TITLE
Add flag useFullPathTableAlias

### PR DESCRIPTION
**Pull request by tonyfulls845**

### CODE REVIEW

**Comment by fico7489** [comment]
You did not describe the purpose of this MR

**Comment by tonyfulls845** [comment]
this is to join one table several times so as not to cause an error that the alias of table is repeated

**Comment by fico7489** [comment]
already done here https://github.com/fico7489/laravel-eloquent-join/commit/e48f5d7fdaef1967dc863d91ed2a002ff197c993

**Comment by tonyfulls845** [comment]
but this solution does not suit me, since there is a case when I need to know the aliases to add conditions on the columns or something similar, when we need to exactly alias of some joined table, my solution more universal than exist.

**Pull request closed without merging**
