### PR TITLE
Allow orderByRaw relation clause

### PR DESCRIPTION
**Pull request by tonyfulls845**

### CODE REVIEW

**Comment by fico7489** [comment]
orderByRaw will not work with joins

**Comment by tonyfulls845** [comment]
Why? It is working including for joined columns. When we need have custom sort by joined columns for example

**Comment by fico7489** [comment]
what is your goal here?

**Comment by tonyfulls845** [comment]
Sorry, I also don't understand why this was done

**Comment by tonyfulls845** [comment]
to be honest, I also don't understand why this was done. considering that it works because the class is inherited

**Pull request closed without merging**
